config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/resultados'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
require 'mechanize'
require 'uri'
require 'phantomjs'
require 'nokogiri'
require 'watir'

class WelcomeController < ApplicationController
	def index
	end

	def resultados
		mechanize = Mechanize.new
		@busqueda = params[:busqueda]
		b = URI.encode(@busqueda)

		@resCultores = Hash.new
		@resMemoria = Hash.new
		@resBN = Hash.new

		puts "Buscando cultores...\n\n"
		pageARPA = mechanize.get('http://arpa.ucv.cl/dic/')
		form = pageARPA.forms.first
		form['buscar'] = @busqueda
		pageARPA = form.submit
		links_cultores = []
		links_cultores << pageARPA.links_with(:href => /id=\d/)
		pageARPA.links_with(:href => /pagina=+\d/).each do |link|
			pageARPA = link.click
			links_cultores << pageARPA.links_with(:href => /id=\d/)
		end
#
		links_cultores.each do |cxp|
			cxp.each do |cultor|
				@resCultores[cultor.text] = "http://arpa.ucv.cl/dic/" + cultor.uri.to_s
			end
		end

		puts "\n\nBuscando en memoriachilena.cl...\n\n"
		browser = Watir::Browser.new :phantomjs
		browser.goto "http://www.memoriachilena.cl/602/w3-propertyvalue-137757.html?_q=offset%3D0%26limit%3D300%26cid%3D502%26keywords%3D"+ b +"%26stageid%3D100%26searchmode%3Dpartial%26pvid_or%3D509%3A158494%2C26262%2C1224%2C616%2C137551"
		begin
			pagina = Nokogiri::HTML.parse(browser.html)
			titulos = pagina.xpath("//div/h4/a")
		end while titulos.length == 0

		titulos.each do |titulo|
			@resMemoria[titulo.attribute("title").to_s] = "http://www.memoriachilena.cl/602/" + titulo.attribute("href").to_s
		end

		puts "\n\nBuscando en el Archivo de la Biblioteca Nacional... \n\n"
		pagina = "http://descubre.bibliotecanacional.cl/primo_library/libweb/action/myAccountMenu.do?vid=BNC"
		pageBN = mechanize.get(pagina)
		form = pageBN.forms()
		form[1].field_with(:name => "prefes(bulkSize)").value = 1000000
		form[1].submit
		pageBN = Nokogiri::HTML.parse(mechanize.get("http://descubre.bibliotecanacional.cl/primo_library/libweb/action/search.do?ct=facet&fctN=facet_domain&fctV=Archivo+de+M%C3%BAsica&rfnGrp=1&rfnGrpCounter=1&dscnt=0&frbg=&scp.scps=scope%3A(bnc_digitool)%2Cscope%3A(bnc_memoria)%2Cscope%3A(bnc_dtlmarc)%2Cscope%3A(BNC)&tab=bnc_tab&dstmp=1460467864295&srt=rank&ct=search&mode=Basic&&dum=true&indx=1&vl(freeText0)=" + b + "&fn=search&vid=BNC").body)
		titulosBN = pageBN.xpath("//div/h2/a")
		titulosBN.each do |titulo|
			if titulo.attribute("href") =~ /http:\/\/descubre.bibliotecanacional.cl.*/
				@resBN[titulo.text.strip] = titulo.attribute("href")
			else
				@resBN[titulo.text.strip] = "http://descubre.bibliotecanacional.cl/primo_library/libweb/action/" + titulo.attribute("href")
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Prueba</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<div class="row">
			<%= link_to root_path do %>
			<%= image_tag("logo_bn.jpg") %>
			<% end %>
			<!-- Main jumbotron for a primary marketing message or call to action -->
		</div>
		<div class="row">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li><a href="#">Quiénes Somos</a></li>
						<li><a href="#">Servicios</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Colecciones<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">DD</a></li>                   
							</ul>
						</li>
						<li><a href="#">Catálogo</a></li>
						<li><a href="#">Biblioteca Nacional Digital</a></li>
					</ul>
					<div class="col-sm-3 col-md-3 pull-right">
						<div class="input-group">
							<%= form_tag(welcome_resultados_path, :method => "get", id: "search-form", class: "navbar-form") do %>

							<%= text_field_tag :search, params[:search], placeholder: "Buscar", class:"form-control", name:"busqueda" %>
							<div class="input-group-btn">
								<%= button_tag(type: "sumbit", class: "btn btn-default") do %>
								<i class="glyphicon glyphicon-search"></i>
								<% end %>
							</div>

							<% end %>
						</div>	
					</div>        
				</div>
			</nav>
		</div>
		<div class="row">
			<div class="col-md-3">
				<div class="list-group">
					<a href="#" class="list-group-item">Cartelera</a>
					<a href="#" class="list-group-item">Galerías</a>
					<a href="#" class="list-group-item">Noticias</a>
					<a href="#" class="list-group-item">Publicaciones</a>
				</div>
			</div>
			<div class="col-md-9">
			
				<%= yield %>

			</div>
		</div>
		<div class="row panel-footer">Panel footer</div>
	</div>

</body>
</html>

app/views/welcome/index.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="col-md-3">
        <%= image_tag("logo_bn.jpg") %>
      </div>
      <div class="col-md-9">
        <h2>Título noticia</h2>
        <p>Cuerpo</p>
      </div>
    </div>

    <div class="item">
      <div class="col-md-3">
        <%= image_tag("logo_bn.jpg") %>
      </div>
      <div class="col-md-9">
        <h2>Título noticia</h2>
        <p>Cuerpo</p>
      </div>
    </div>

    <div class="item">
      <div class="col-md-3">
        <%= image_tag("logo_bn.jpg") %>
      </div>
      <div class="col-md-9">
        <h2>Título noticia</h2>
        <p>Cuerpo</p>
      </div>
    </div>

    <div class="item">
      <div class="col-md-3">
        <%= image_tag("logo_bn.jpg") %>
      </div>
      <div class="col-md-9">
        <h2>Título noticia</h2>
        <p>Cuerpo</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="row">
<h2>Destacados</h2>
  <div class="col-md-3"><%= image_tag("logo_bn.jpg") %></div>
  <div class="col-md-9">
    <h3>Destacado</h3>
    <p>Cuerpo: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>

app/views/welcome/resultados.html.erb
<h2>Resultados de búsqueda por "<%= @busqueda %>"</h2>

<h3>ARPA</h3>
<% @resCultores.each do |res| %>
	<%= link_to(res[0], res[1], method: :delete,:target => '_blank') %>
<% end %>
<h3>Memoria Chilena</h3>
<% @resMemoria.each do |res| %>
	<%= link_to(res[0], res[1], method: :delete,:target => '_blank') %>
<% end %>
<h3>Biblioteca Nacional</h3>
<% @resBN.each do |res| %>
	<%= link_to(res[0], res[1], method: :delete,:target => '_blank') %>
<% end %>